---
- name: "Set autologin for kali user"
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^#autologin-user="
    line: "autologin-user={{ ansible_user_id }}"

- name: "Disable power manager"
  become: true
  become_method: sudo
  ansible.builtin.command: xfconf-query -c xfce4-power-manager -p '/xfce4-power-manager/dpms-enabled' -s 'false'