---
- name: "Set autologin for kali user"
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^#autologin-user="
    line: "autologin-user={{ ansible_user_id }}"